name: ci
run-name: ${{ github.actor }} is pushing the code to DockerHub
on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: vignesh9123/todo:${{ github.sha }}

      -
        name: SSH and Push to EC2
        run: |
          echo "${{secrets.EC2_PRIVATE_KEY}}" > ~/ssh_key
          chmod 700 ~/ssh_key 
          ssh -o StrictHostKeychecking=no -i ~/ssh_key ubuntu@13.201.21.179 "sudo docker stop nextweb && sudo docker pull vignesh9123/todo:${{ github.sha }} && sudo docker container prune -f && sudo docker run --name nextweb -d -p 3000:3000 vignesh9123/todo:${{ github.sha }}" 